manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: ethangrunewald
      url-base: https://github.com/Ethan-Grunewald
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: nice-view-mod
      remote: ethangrunewald
      revision: main
  self:
    path: config
